// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC9saYjGQHPmHT3ZDHfgyDXEcwZHymvB8',
    appId: '1:339611448491:web:674b3e2c83f28a248833ee',
    messagingSenderId: '339611448491',
    projectId: 'aethercore-37150',
    authDomain: 'aethercore-37150.firebaseapp.com',
    storageBucket: 'aethercore-37150.firebasestorage.app',
    measurementId: 'G-1XJ1LPHMJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB69jSViG6dGVANxCVMEQLm6EG8L-VE9U0',
    appId: '1:339611448491:android:89eb167bdb6b38ee8833ee',
    messagingSenderId: '339611448491',
    projectId: 'aethercore-37150',
    storageBucket: 'aethercore-37150.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBoJgj_22vVxo54qb1Y9vMT-CafvT5ahI',
    appId: '1:339611448491:ios:96d2d1081e6188618833ee',
    messagingSenderId: '339611448491',
    projectId: 'aethercore-37150',
    storageBucket: 'aethercore-37150.firebasestorage.app',
    iosBundleId: 'com.example.aethercore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBoJgj_22vVxo54qb1Y9vMT-CafvT5ahI',
    appId: '1:339611448491:ios:96d2d1081e6188618833ee',
    messagingSenderId: '339611448491',
    projectId: 'aethercore-37150',
    storageBucket: 'aethercore-37150.firebasestorage.app',
    iosBundleId: 'com.example.aethercore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC9saYjGQHPmHT3ZDHfgyDXEcwZHymvB8',
    appId: '1:339611448491:web:ae2f2b36684996908833ee',
    messagingSenderId: '339611448491',
    projectId: 'aethercore-37150',
    authDomain: 'aethercore-37150.firebaseapp.com',
    storageBucket: 'aethercore-37150.firebasestorage.app',
    measurementId: 'G-D0MLFC7YMJ',
  );
}
